sudo: required
dist: trusty
language: node_js
node_js:
  - '6.11.0'
  - 'stable'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  firefox: 'latest'
cache:
  directories:
    - node_modules
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: aI/15mOf66vVy4iUV9Bw+nu1YJwunKxkH0CU3Uodn7c8GnuixKpdjGu0ljPk07uZXYBzDxRDUeEE2Gnov6rL1GmMQqW0nrKdU0IXms3ZY0WMz5NEVh3soVqLpAlqh/WfYvdW/kfiiIlIRlxBCVcWuZrOJSDQNU0VMrTHysi2ajeqkn7QaPgX9n38iZbPmAI8+4IzHsLF4mJhY6MfzBn7y29Yltuuib0aQLwZl6Lr8gbJZbgyIw1LAKB4n9RjMiXJ+aGzr6V0gxEtaU8WwTnDrFoH1hY/6+FeaRwvID2KXJ+PmmZUwoPochbR1a33Rb/baUUIdjB8aZPxhTyoEdB7r/NVsPJYXYSzRLmyIrs3ECsd0kMDYRdas34S9UOLWN9DNHaOAHZ2Gn5QbqzsP6YAX8fcYoGFR3Z8Q5XqCLA4bikSMpVecrRKFKT9+eoJwJpM7bO1PiqMsWFepT3qDoG4egj8A7iHJ/y0Zkk87/3iKYr2pmBLzEsMd+tfRKoyGr13Jg4SnDUdWomRWFDqeBzajHJ7XfVOOvOhM7JQ5/7WALrsTRfe/Q9WRLg7CWKPRUS4LcePMDXiZfoN0jhxLl4Rr/l6ZzO/gA09TmT1yL0VOeXcaZcDCY5HfFQPS59PjHhhuw8AuDjkqIR2I080122gBk+Wy3CLYb/ITKGiWw5vHFI=
before_install:
  - npm config set spin false
  - npm install -g coveralls pr-bumper@^2.0.0 ciena-devops^1.0.0
  - $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh
install:
  - $(npm root -g)/pr-bumper/.travis/maybe-install.sh
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - $(npm root -g)/pr-bumper/.travis/maybe-test.sh
  - .travis/maybe-bump-version.sh
after_success:
  - .travis/maybe-publish-coverage.sh
after_deploy:
- $(npm root -g)/ciena-devops/scripts/slack/incoming-webhooks/send-message.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: br1VPEEXdNExe1/FmOHTOKLFMttgwRbUzcGWl4Stq1CpjYz93lkUL4F5z+AijG/nIZUptRmDVF97P1HCp8Ji5YlflO+ab4zjQBb/u8STU6A0nclUSULiPj2SQ/Ajp7avtJFgw4JBkMWIBcKHDkLRKD0Gg1A8Uza5jjp+6Rp2RaQVOqgDEHiONBb8dISxBn2SsZW/cYo6WRahqm51nQPbzLXn/p35X4GHHH+oipx3f4PChvt02jzqLH1mHR3QsHksuWDphueNu+XWGaM8xPV8cVQzBN9JmN1X2a24Ov4+sqbTagdKGGCivUEkDeZVV4B5Wf5Ss5L0IsWVSJIAVnG6EGeh/U/Vv7mHVt9z9cnOGEg4ffeokW8zCpp7vU/VDolYDnPZfm/TtHQjQ4VO04wyY7A62QJG/KlU3x0N/8vmI1IIv3llgdDK5JGtNG3QfaaahLouKdf4pLSRku5QpzN0uRh0JxeQG70PcIiUU4w9me3gdbfn2Fp+Chu0Fz1q1PwpdxeKhzKnKkCJOf7obTBx7JWGk9ZpKCCWONpsdRvd3krLyYDzYsj+bq7QjHCbYgVfpKB+M39garEMjvdA9X+fHZGXIOHA7SEQsFq9WvUDdDd6VvQrbKiYyjYVeGCdzpB6aFGS0I3iX58oChjJRl6WCG1t7KnLW7Qusm2aamn3Wtw=
  on:
    all_branches: true
    node: '6.11.0'
    tags: true
notifications:
slack:
  secure: k4mneZ/E8t0ifeHfLIdeWAjTyB66XN0vLA7dzNAPZgXM1JF9RMJseMLttvrfvGReN9f+dwN1hKnGeXBEhtL9CYO7mF+WCtjhQcM8w3FrZ19YGOj9fcKflkelqjmCJsbir6t197LUfeD9m9n7WGHkpi9UMRfdq1jz2lEXAF/D3LLcrI91tFZ2uOa0dan6GDEoB+QW6enxcANiCQ63iZ4C4Jon5DD9oy422ZF2Nq380ggRCpJZCwDf1/owxAUW9o+YP4pyHHis4rpbIhw0aRpJzlZyRwku+dFpQA1RaQAVSqaImICm4DZm9AUvQJtLfnODjdWs7glpZeQb0ltqownNUX5DJy3NKrSy9wz53bNZ1akeZTLYlk4KhjeWecaVRA29LaSB4JKdq0gxBYEyGrtUXLDQRiZiPyNTMFYQs/tBBs3fwzbJgGJHu+iPgQnUNM//AmFD1SOcteRoOb1yNwvN7BY6J0O/TDeriCARfqrSiPpn5452q0rDsDVDp369D15X52E4lz8AkkdVI1iV6i4A+crP6JkyyHE47xkGQW3yNMUSBg97zbjEBV0ekHxnzrfIlrPXvuEMsxR8sEpV7oBR06B/aKvz1DNrb97Xs9fmx7CGug9JG7+ZssYSEgKeSdolmIId6VODHMKQWs3jsLWDSJRB/V9Q9Agi7fXmZr3uRG8=
